---
stitle: "COVID-19 State Policies"
author: "Bernice Boursiquot"
date: "2023-02-10"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

dataPath = "/Users/bernice/Documents/covid state policies/"

library(dplyr)
library(tidyr)
```

```{r Importing data}

dataFile = file.path("/Users", "bernice", "Documents", "covid state policies","data", "COVID-19 US state policy database 3_30_2022.xlsx")

readxl::excel_sheets(dataFile)

dataDictionary = 
  readxl::read_xlsx(dataFile, sheet = 1, n_max = 4)

statePolicychanges = 
  readxl::read_xlsx(dataFile, sheet = 1) %>%
    filter(!row_number() %in% c(1:4))


```

```{r Exploring data}

head(statePolicychanges)

colnames(statePolicychanges)

attributeType = tibble(rowId = c("variableName", "policyCategory", "variableType", "variableFormat"))

typeof(attributeType)

c(attributeType,dataDictionary)

y =  tibble(attributeType, dataDictionary) 

y %>%
  pivot_wider(names_from = rowId, values_from = 2:287)

y$rowId

dataDictionary2 = 
  tibble(attributeType, dataDictionary) %>% 
    pivot_longer(everything(), values_to = "variableDescriptor", names_to = "variableName") %>%
      arrange(variableName)

#Policy Types



```
